import jsPDF from 'jspdf';
import { log } from './logger';

/**
 * PDF Export Engine for Naksha
 * Programmatic generation of A4 multi-page reports.
 */

export async function exportChartPDF(profile, chartData, insights) {
  if (!profile || !chartData) {
    throw new Error('Incomplete data for PDF export');
  }

  const { positions, ascendant, dashaTimeline, currentDasha, yogas } = chartData;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210, H = 297;
  const margin = 20;

  const addFooter = (pageNum) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by Naksha — naksha.app | Page ${pageNum}`, W / 2, H - 10, { align: 'center' });
  };

  const drawBackground = () => {
    doc.setFillColor(8, 11, 20);
    doc.rect(0, 0, W, H, 'F');
  };

  const drawPageHeader = (title) => {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(59, 130, 246);
    doc.text(title, margin, 25);
  };

  // --- PAGE 1: COVER ---
  drawBackground();
  
  // Top accent line
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.5);
  doc.line(margin, 15, W - margin, 15);

  // App name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.text('NAKSHA', W / 2, 40, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(150, 150, 150);
  doc.text('Vedic Birth Chart Report', W / 2, 52, { align: 'center' });

  // Profile info
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text(profile.name, W / 2, 75, { align: 'center' });
  
  doc.setFontSize(11);
  doc.setTextColor(180, 180, 180);
  doc.text(`${profile.dob_date} at ${profile.dob_time}`, W / 2, 85, { align: 'center' });
  
  doc.setFont('courier', 'normal');
  doc.setFontSize(10);
  doc.text(`${profile.latitude.toFixed(4)}N, ${profile.longitude.toFixed(4)}E`, W / 2, 93, { align: 'center' });

  doc.setDrawColor(40, 40, 40);
  doc.line(margin + 20, 105, W - margin - 20, 105);

  // Dasha block
  if (currentDasha) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(59, 130, 246);
    doc.text('CURRENT MAHA DASHA', W / 2, 118, { align: 'center' });
    
    doc.setFontSize(18);
    doc.setTextColor(255, 255, 255);
    doc.text(currentDasha.maha.planet.toUpperCase(), W / 2, 128, { align: 'center' });
    
    doc.setFontSize(8);
    doc.setTextColor(59, 130, 246);
    doc.text('ACTIVE ANTAR DASHA', W / 2, 140, { align: 'center' });
    
    doc.setFontSize(14);
    doc.setTextColor(200, 200, 200);
    doc.text(currentDasha.antar.planet, W / 2, 150, { align: 'center' });
    
    doc.setFont('courier', 'normal');
    doc.setFontSize(9);
    doc.text(`Ends: ${new Date(currentDasha.antar.endDate).toLocaleDateString()}`, W / 2, 160, { align: 'center' });
  }

  // Daily Score
  if (insights) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(59, 130, 246);
    doc.text("TODAY'S COSMIC SCORE", W / 2, 185, { align: 'center' });
    
    doc.setFontSize(32);
    doc.setTextColor(255, 255, 255);
    doc.text(insights.dailyOutlook.score.toString(), W / 2, 200, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(150, 150, 150);
    doc.text(insights.dailyOutlook.title, W / 2, 210, { align: 'center' });

    // Panchang Minimal Strip
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    const panchangStr = `${insights.vara.name} | ${insights.tithi.name} | ${insights.nakshatra.name} | ${insights.yoga.name} | ${insights.karana.name}`;
    doc.text(panchangStr.toUpperCase(), W / 2, 220, { align: 'center' });
  }

  addFooter(1);

  // --- PAGE 2: PLANETS & YOGAS ---
  doc.addPage();
  drawBackground();
  drawPageHeader('PLANETARY POSITIONS — D1 RASHI');

  // Table setup
  const tableY = 35;
  const rowH = 9;
  const colX = [margin, margin + 25, margin + 50, margin + 85, margin + 125, margin + 145];
  const headers = ['Planet', 'Sign', 'Degrees', 'Nakshatra', 'Pad', 'Ret'];

  // Header row
  doc.setFillColor(26, 26, 26);
  doc.rect(margin, tableY, W - (margin * 2), rowH, 'F');
  doc.setFontSize(8);
  doc.setTextColor(200, 200, 200);
  headers.forEach((h, i) => doc.text(h, colX[i] + 2, tableY + 6));

  // Rows
  const sortedPlanets = ['Sun', 'Moon', 'Mars', 'Mercury', 'Jupiter', 'Venus', 'Saturn', 'Rahu', 'Ketu', 'Gulika'];
  const allRows = [
    { name: 'Ascendant', ...ascendant }, 
    ...sortedPlanets.filter(p => positions[p]).map(p => ({ name: p, ...positions[p] }))
  ];

  allRows.forEach((row, i) => {
    const y = tableY + rowH + (i * rowH);
    doc.setFillColor(i % 2 === 0 ? 10 : 0, 10, i % 2 === 0 ? 15 : 0);
    doc.rect(margin, y, W - (margin * 2), rowH, 'F');
    
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text(row.name === 'Ascendant' ? 'Ascendant' : row.name, colX[0] + 2, y + 6);
    
    doc.setTextColor(180, 180, 180);
    // Standard signs helper
    const signNames = ['Ar', 'Ta', 'Ge', 'Ca', 'Le', 'Vi', 'Li', 'Sc', 'Sa', 'Cp', 'Aq', 'Pi'];
    doc.text(signNames[row.sign], colX[1] + 2, y + 6);
    
    doc.setFont('courier', 'normal');
    doc.text(`${(row.longitude % 30).toFixed(2)}°`, colX[2] + 2, y + 6);
    
    doc.setFont('helvetica', 'normal');
    doc.text(row.nakshatra || '-', colX[3] + 2, y + 6);
    doc.text(row.pada?.toString() || '-', colX[4] + 2, y + 6);
    
    if (row.retrograde) {
      doc.setTextColor(239, 68, 68);
      doc.text('R', colX[5] + 2, y + 6);
    } else {
      doc.text('-', colX[5] + 2, y + 6);
    }
  });

  // Yogas
  const yogaY = 140;
  drawPageHeader('DETECTED YOGAS');
  doc.setLineWidth(0.1);
  doc.setDrawColor(30, 30, 30);
  doc.line(margin, yogaY + 5, W - margin, yogaY + 5);

  if (yogas && yogas.length > 0) {
    yogas.slice(0, 8).forEach((yoga, i) => {
      const y = yogaY + 15 + (i * 14);
      
      // strength dot
      doc.setFillColor(yoga.strength === 'Strong' ? 34 : 59, yoga.strength === 'Strong' ? 197 : 130, yoga.strength === 'Strong' ? 94 : 246);
      doc.circle(margin + 2, y - 1, 1, 'F');
      
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.text(yoga.name, margin + 6, y);
      
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(yoga.description, margin + 6, y + 5, { maxWidth: W - margin * 2 - 10 });
    });
  } else {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('No major yogas detected.', margin, yogaY + 15);
  }

  addFooter(2);

  // --- PAGE 3: TIMELINE ---
  doc.addPage();
  drawBackground();
  drawPageHeader('VIMSHOTTARI DASHA TIMELINE');

  const timelineX = 30;
  const startY = 40;
  const spacing = 26;

  // Vertical line
  doc.setDrawColor(40, 40, 40);
  doc.setLineWidth(1);
  doc.line(timelineX, startY, timelineX, startY + (spacing * 8));

  dashaTimeline.slice(0, 9).forEach((d, i) => {
    const y = startY + (i * spacing);
    const isActive = d.planet === currentDasha?.maha.planet;

    // Dot
    doc.setFillColor(isActive ? 59 : 100, isActive ? 130 : 100, isActive ? 246 : 100);
    doc.circle(timelineX, y, 2, 'F');

    if (isActive) {
      // Active indicator
      doc.setFillColor(59, 130, 246, 0.1);
      doc.rect(timelineX + 5, y - 5, 80, 10, 'F');
      
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(59, 130, 246);
      doc.text('YOU ARE HERE', timelineX + 5, y - 7);
    }

    doc.setFont('helvetica', isActive ? 'bold' : 'normal');
    doc.setFontSize(isActive ? 11 : 9);
    doc.setTextColor(isActive ? 255 : 150, isActive ? 255 : 150, isActive ? 255 : 150);
    doc.text(`${d.planet} Maha Dasha`, timelineX + 8, y + 1);
    
    doc.setFont('courier', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    const dateStr = `${d.startDate.getFullYear()} — ${d.endDate.getFullYear()}`;
    doc.text(dateStr, timelineX + 8, y + 6);
  });

  addFooter(3);

  // --- EXPORT ---
  const profileName = profile.name.replace(/\s+/g, '_');
  const filename = `Naksha_${profileName}_${new Date().toISOString().split('T')[0]}.pdf`;
  
  try {
    doc.save(filename);
    log.info('PDFExport', 'Chart exported successfully', { filename });
  } catch (err) {
    log.error('PDFExport', `Failed to save PDF: ${err.message}`);
    throw err;
  }
}
